<?php include 'inc/functions.php'; ?>
<?php include 'inc/header.phtml'; ?>
    <form id="search-form" action="/users" method="get">
        <div>
            <input class="form-control form-control-inline form-control-sm pull-right" id="search_for" name="search_for" type="text" value="" placeholder="Search..." size="20" />
        </div>
        <div>
            <select class="form-control form-control-inline form-control-sm pull-right" name="search_by" id="search_by">
            </select>
        </div>
        <div>
            <button class="btn btn-sm btn-outline-primary search-btn text-uppercase">Search</button>
            <a class="btn btn-sm btn-outline-primary text-uppercase" id="export-btn" href="/users/export">Export</a>
            <a class="btn btn-sm btn-outline-primary text-uppercase" href="/users">Reset</a>
            <input type="hidden" name="fields" id="fields" value="" />
        </div>
    </form>
    <div id="field-checkboxes">
    </div>
    <h1 id="results-header"><?=$title; ?></h1>
    <table id="results" class="table table-bordered table-striped table-hover"
           data-url="<?=$apiUrl; ?>"
           data-page="<?=(int)$page; ?>"
           data-limit="<?=(int)$limit; ?>"
           data-sort="<?=$sort; ?>"
           data-filter="<?=(!empty($filter) && is_array($filter)) ? implode(',', $filter) : $filter; ?>"
           data-fields="<?=$fields; ?>"
           data-numbered="1">
        <thead>
        </thead>
        <tbody>
        </tbody>
    </table>
    <div id="loading"></div>
    <div id="no-results"><h4>No users were found.</h4></div>
<?php include 'inc/footer.phtml'; ?>