<?php include 'inc/functions.php'; ?>
<?php include 'inc/header.phtml'; ?>
    <h1 id="results-header"><?=$title; ?></h1>
    <table id="results" class="table table-bordered table-striped table-hover" cellpadding="0" cellspacing="0"
           data-url="http://mock-api.localhost/users"
           data-page="<?=(int)$page; ?>"
           data-limit="<?=(int)$limit; ?>"
           data-sort="<?=$sort; ?>"
           data-filter="<?=implode(',', $filter); ?>"
           data-fields="<?=implode(',', $fields); ?>"
           data-numbered="<?=$numbered; ?>">
        <thead>

        </thead>
        <tbody>

        </tbody>
    </table>
    <div id="loading"></div>
<?php include 'inc/footer.phtml'; ?>