<?php include 'inc/functions.php'; ?>
<?php include 'inc/header.phtml'; ?>
    <form id="search-form" action="/users" method="get">
        <div>
            <input class="form-control form-control-inline form-control-sm pull-right" id="search_for" name="search_for" type="text" value="" placeholder="Search..." size="20" />
        </div>
        <div>
            <select class="form-control form-control-inline form-control-sm pull-right" name="search_by" id="search_by">
            </select>
        </div>
        <div>
            <button class="btn btn-sm btn-primary search-btn text-uppercase" title="Search"><i class="fa fa-search"></i></button>
            <a class="btn btn-sm btn-primary text-uppercase" id="export-btn" href="/users/export" title="Export"><i class="fa fa-arrow-down"></i></a>
            <a class="btn btn-sm btn-primary text-uppercase" href="/users" title="Reset"><i class="fa fa-refresh"></i></a>
<?php if (!$pageView): ?>
            <a href="/users?scroll=0" class="btn btn-sm btn-primary" title="Page View"><i class="fa fa-copy"></i></a>
<?php else: ?>
            <a href="/users" class="btn btn-sm btn-primary" title="Scroll View"><i class="fa fa-angle-double-down"></i></a>
            <input type="hidden" name="scroll" value="0"/>
<?php endif; ?>
            <input type="hidden" name="fields" id="fields" value="" />
        </div>
    </form>
    <div id="field-checkboxes">
    </div>
    <h1 id="results-header"><?=$title; ?></h1>
    <table id="results" class="table table-bordered table-striped table-hover"
           data-url="<?=$apiUrl; ?>"
           data-page="<?=(int)$page; ?>"
           data-limit="<?=(int)$limit; ?>"
           data-sort="<?=$sort; ?>"
           data-filter="<?=(!empty($filter) && is_array($filter)) ? implode(',', $filter) : $filter; ?>"
           data-fields="<?=$fields; ?>"
           data-numbered="1">
        <thead>
        </thead>
        <tbody>
        </tbody>
    </table>
<?php if (isset($paginator)): ?>
    <ul class="pagination pagination-sm justify-content-center">
        <?=$paginator; ?>
    </ul>
<?php else: ?>
    <div id="loading"></div>
    <div id="scroll-top"><a href="#" class="btn btn-secondary btn-block btn-sm"><i class="fa fa-angle-double-up"></i></a></div>
<?php endif; ?>
    <div id="no-results"><h4>No users were found.</h4></div>
<?php include 'inc/footer.phtml'; ?>